# Generated by Django 3.2.6 on 2021-09-09 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tasklog',
            name='duration_gt_0',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
