# Generated by Django 3.2.6 on 2021-09-09 17:16

from django.db import migrations
from django.utils.timezone import now as timezone_now


def forwards(apps, schema_editor):
    TaskLog = apps.get_model("tracking", "TaskLog")
    db_alias = schema_editor.connection.alias
    TaskLog.objects.using(db_alias).filter(stop__isnull=True).update(
        stop=timezone_now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_auto_20210909_1713"),
    ]

    operations = [migrations.RunPython(forwards)]
